name: Run AI Script Daily

on:
  schedule:
    - cron: '00 17 * * *'  # 00:00 Việt Nam
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (start/stop)'
        required: true
        default: 'start'

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      CUDA_VISIBLE_DEVICES: ""  # Disable GPU
      TF_CPP_MIN_LOG_LEVEL: "3"  # Suppress TensorFlow warnings
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libblas-dev liblapack-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install tensorflow==2.17.0 -v
          pip install -r requirements.txt

      - name: Check dependency conflicts
        run: |
          pip check

      - name: Run Script
        run: |
          if [ "${{ github.event.inputs.action }}" = "start" ]; then
            echo "Starting bot..."
            python bai_viet.py
          else
            echo "Stop action not supported without persistent process."
            exit 1
          fi